USE [master]
GO
/****** Object:  Database [ToysStore]    Script Date: 07/09/2014 14:24:02 ******/
CREATE DATABASE [ToysStore]
GO

ALTER DATABASE [ToysStore] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ToysStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ToysStore] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ToysStore] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ToysStore] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ToysStore] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ToysStore] SET ARITHABORT OFF 
GO
ALTER DATABASE [ToysStore] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ToysStore] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [ToysStore] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ToysStore] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ToysStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ToysStore] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ToysStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ToysStore] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ToysStore] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ToysStore] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ToysStore] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ToysStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ToysStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ToysStore] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ToysStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ToysStore] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ToysStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ToysStore] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ToysStore] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ToysStore] SET  MULTI_USER 
GO
ALTER DATABASE [ToysStore] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ToysStore] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ToysStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ToysStore] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [ToysStore]
GO
/****** Object:  Table [dbo].[AgeRanges]    Script Date: 07/09/2014 14:24:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AgeRanges](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MinimumAge] [int] NOT NULL,
	[MaximumAge] [int] NULL,
 CONSTRAINT [PK_AgeRanges] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Categories]    Script Date: 07/09/2014 14:24:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Manufacturers]    Script Date: 07/09/2014 14:24:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Manufacturers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
	[Country] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Manufacturers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Toys]    Script Date: 07/09/2014 14:24:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Toys](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](60) NOT NULL,
	[Type] [nvarchar](20) NULL,
	[Price] [money] NOT NULL,
	[Color] [nvarchar](20) NULL,
	[ManufacturerId] [int] NOT NULL,
	[AgeRangeId] [int] NULL,
 CONSTRAINT [PK_Toys] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ToysCategories]    Script Date: 07/09/2014 14:24:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ToysCategories](
	[ToyId] [int] NOT NULL,
	[CategoryId] [int] NOT NULL,
 CONSTRAINT [PK_ToysCategories] PRIMARY KEY CLUSTERED 
(
	[ToyId] ASC,
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_Manufacturers]    Script Date: 07/09/2014 14:24:02 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Manufacturers] ON [dbo].[Manufacturers]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Toys]  WITH CHECK ADD  CONSTRAINT [FK_Toys_AgeRanges] FOREIGN KEY([AgeRangeId])
REFERENCES [dbo].[AgeRanges] ([Id])
GO
ALTER TABLE [dbo].[Toys] CHECK CONSTRAINT [FK_Toys_AgeRanges]
GO
ALTER TABLE [dbo].[Toys]  WITH CHECK ADD  CONSTRAINT [FK_Toys_Manufacturers] FOREIGN KEY([ManufacturerId])
REFERENCES [dbo].[Manufacturers] ([Id])
GO
ALTER TABLE [dbo].[Toys] CHECK CONSTRAINT [FK_Toys_Manufacturers]
GO
ALTER TABLE [dbo].[ToysCategories]  WITH CHECK ADD  CONSTRAINT [FK_ToysCategories_Categories] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([Id])
GO
ALTER TABLE [dbo].[ToysCategories] CHECK CONSTRAINT [FK_ToysCategories_Categories]
GO
ALTER TABLE [dbo].[ToysCategories]  WITH CHECK ADD  CONSTRAINT [FK_ToysCategories_Toys] FOREIGN KEY([ToyId])
REFERENCES [dbo].[Toys] ([Id])
GO
ALTER TABLE [dbo].[ToysCategories] CHECK CONSTRAINT [FK_ToysCategories_Toys]
GO
USE [master]
GO
ALTER DATABASE [ToysStore] SET  READ_WRITE 
GO
