//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task04StringOccurrenceService.Client.StringOccurrenceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringOccurrenceService.IStringCounter")]
    public interface IStringCounter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCounter/CountHowMuchTimesStringApersInOtherString", ReplyAction="http://tempuri.org/IStringCounter/CountHowMuchTimesStringApersInOtherStringRespon" +
            "se")]
        int CountHowMuchTimesStringApersInOtherString(string text, string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCounter/CountHowMuchTimesStringApersInOtherString", ReplyAction="http://tempuri.org/IStringCounter/CountHowMuchTimesStringApersInOtherStringRespon" +
            "se")]
        System.Threading.Tasks.Task<int> CountHowMuchTimesStringApersInOtherStringAsync(string text, string word);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringCounterChannel : Task04StringOccurrenceService.Client.StringOccurrenceService.IStringCounter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringCounterClient : System.ServiceModel.ClientBase<Task04StringOccurrenceService.Client.StringOccurrenceService.IStringCounter>, Task04StringOccurrenceService.Client.StringOccurrenceService.IStringCounter {
        
        public StringCounterClient() {
        }
        
        public StringCounterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringCounterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCounterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCounterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountHowMuchTimesStringApersInOtherString(string text, string word) {
            return base.Channel.CountHowMuchTimesStringApersInOtherString(text, word);
        }
        
        public System.Threading.Tasks.Task<int> CountHowMuchTimesStringApersInOtherStringAsync(string text, string word) {
            return base.Channel.CountHowMuchTimesStringApersInOtherStringAsync(text, word);
        }
    }
}
